apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: bidrag-dokument-bestilling
  namespace: bidrag
  labels:
    team: bidrag
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: bidrag
  secretName: {{unleash.secret_name}}

  # Specify which environment the API token should be created for.
  # Can be one of: development, or production.
  environment: {{unleash.env}}