package no.nav.bidrag.dokument.bestilling.bestilling.dto

object BestillingSystem {
    const val BREVSERVER = "BREVSERVER"
}

enum class BrevType {
    UTGÅENDE,
    NOTAT
}
typealias BestillingSystemType = String

enum class BrevKode(val beskrivelse: String, var brevtype: BrevType, val bestillingSystem: BestillingSystemType, val batchbrev: Boolean = false, val enabled: Boolean = true) {
    BI01P11("NOTAT P11 T", BrevType.NOTAT, BestillingSystem.BREVSERVER),
    BI01P18("Saksbehandlingsnotat", BrevType.NOTAT, BestillingSystem.BREVSERVER),
    BI01X01("REFERAT FRA SAMTALE", BrevType.NOTAT, BestillingSystem.BREVSERVER),
    BI01X02("ELEKTRONISK DIALOG", BrevType.NOTAT, BestillingSystem.BREVSERVER),
    BI01S10("KOPIFORSIDE T", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER),
    BI01S67("ADRESSEFORESPØRSEL", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER),
    BI01S02("Fritekstbrev", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER),
    BI01S09("Varsel opphør bidrag v 18 år", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),

    BI01G01("Vedtak innkrev. barnebidrag og gjeld", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01G02("Vedtak innkreving opphør", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S19("Innkreving varsel til motparten", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01B50("Klage - vedtak bidrag", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01G50("Klage - vedtak innkreving", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01P17("Innstilling til klageinstans", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S20("Klage varsel til motparten", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S21("Klage orientering til klageren", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S60("Infobrev til partene oversendelse klageinstans", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S61("Innhenting opplysninger paragraf 10 i barnelova", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S64("Varsel klage fvt 35", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S65("Varsel om motregning", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S68("Varsel om overføring KO-fogd", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01B10("Opphørsvedtak", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S07("Fastsettelse eget tiltak varsel til BP", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01B01("Vedtak barnebidrag", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01B04("Revurdering Bidrags pga forskudd", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01B05("VEDTAK AUTOMATISK JUSTERING BARNEBIDRAG", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01B20("Vedtak utland skjønn fastsettelse", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01B21("Vedtak utland skjønn endring", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S06("Varsel eget tiltak nyfødt barn", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S31("Fasts. eget tiltak uten innkr varsel til partene", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S32("Fastsettelse eget tiltak varsel til BM", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S33("Endring varsel eget tiltak pga 25%", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S34("Endring varsel eget tiltak pga barnetillegg", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S35("Endring varsel eget tiltak pga forholds fordel", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S36("Endring varsel eget tiltak pga forsørgingstillegg", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S46("Varsel oppfostringsbidrag forholdsmessig fordeling", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S62("Fastsettelse bidrag barnetillegg varsel partene", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S63("Fastsettelse bidrag forsørgingstillegg varsel", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S70("Varsel om eget tiltak trekkes", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S22("Revurd bidrag pga FO til BM", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S23("Revurd bidrag pga FO til BP", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S01("Fastsettelse varsel til motparten", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S12("Fastsettelse orientering til BM", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S52("Fastsettelse oppfostringsbidrag orienter kommune", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S53("Fastsettelse oppfostringsbidrag varsel til BP", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S13("Fastsettelse orientering til BP", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01B02("Vedtak tilleggsbidrag", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S05("Ettergivelse varsel til motparten", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S14("Endring orientering til søkeren", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S26("Endring varsel til motparten", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S47("Endring oppfostringsbidrag orientering til BP", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S48("Endring oppfostringsbidrag orientering kommune", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S49("Endring oppfostringsbidrag varsel til motparten", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01I50("Klage - vedtak ektefellebidrag", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01I01("Vedtak ektefellebidrag", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S43("Fastsettelse ektefellebidrag orientering", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S44("Fastsettelse ektefellebidrag varsel til BP", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S37("Bortfall ektefellebidrag BP død orientering til BM", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S38("Bortfall ektefellebidrag orientering til partene", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S39("Bortfall ektefellebidrag nytt ekteskap orientering", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S41("Vedtak - bortfall nytt ekteskap", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S42("Endring ektefellebidrag orientering til søkeren", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01A50("Klage - vedtak forskudd", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, true),
    BI01A01("Vedtak forskudd", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, true),
    BI01A04("Revurdering forskudd settes ned", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, true),
    BI01S08("Varsel revurd forskudd", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S27("Varsel opph tilbake i tid §2 ikke opphold i Riket", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S28("Varsel opph tilbake i tid §2 partene bor sammen", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S29("Varsel opph tilbake i tid §3 direkte betalinger", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S30("Varsel opph tilbake i tid §6 ikke omsorg", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S45("Varsel revurd forskudd tilbake i tid", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01H01("Farskap innkalling mor", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01H03("Melding om blodprøver i farskapsak", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01H04("Pålegg om å framstille barn for å gi blodprøve", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01H05("Pålegg om blodprøve i farskapssak", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01H02("Innkalling farskapssak oppgitt far", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S25("Info til BM når farskap OK", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01J50("Klage - vedtak gebyr", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S03("18 år varsel til motparten", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01K50("Klage - vedtak tilbakekreving", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01A05("Vedtak ikke tilbakekreving", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01G04("Vedtak innkreving særtilskudd", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01E50("Klage - vedtak særtilskudd", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01E01("Vedtak særtilskudd innvilget", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01E02("Vedtak særtilskudd avslag", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01E03("Vedtak særtilskudd tannregulering", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S04("Særtilskudd varsel til motparten", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S18("Særtilskudd orientering til søkeren", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01F50("Klage - vedtak ettergivelse gjeld", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01F01("Vedtak ettergivelse innvilget", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01F02("Vedtak ettergivelse avslag", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S17("Ettergivelse varsel til søkeren", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S50("Ettergivelse oppfostringsbidrag orientering til BP", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S51("Ettergivelse oppfostringsbidrag varsel kommune", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01A02("Vedtak tilbakekreving", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S54("Varsel tilb.kr. paragraf 5 inntekt", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S55("Varsel tilb.kr. paragraf 2 - partene bor sammen", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S56("Varsel tilb.kr. paragraf 2 ikke opphold i Riket", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S57("Varsel tilb.kr. NAV paragraf 3 direkte betalinger", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S58("Varsel tilb.kr. NAV paragraf 6 ikke omsorg", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S59("Orientering ettergivelse av tilbakekrevingsbeløp", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S24("STANDARDBREV OM INNHENTING AV OPPLYSNINGER 18år", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01B03("Vedtak barnebidrag over 18 år", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S15("18år orientering til BP", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01S16("18år orientering til BM", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false),
    BI01B11("Vedtak tilleggsbidrag over 18 år", BrevType.UTGÅENDE, BestillingSystem.BREVSERVER, false, false)
}
